# Generated by Django 4.1.6 on 2023-02-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_colors_alter_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('D', 'Percent'), ('M', 'Money')], default='M', max_length=10),
        ),
    ]
