# Generated by Django 4.1.6 on 2023-02-17 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_is_sub_alter_category_parent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.discount'),
        ),
    ]
