# Generated by Django 4.1.6 on 2023-02-22 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_total_price_alter_orderdetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='order.discountcode'),
        ),
    ]
